version: '3'
services:
  open-rdma:
    image: ${IMAGE_REPO:-open-rdma}:${TAG:-latest}
    build: .
    privileged: true
    tty: true
    stdin_open: true
    ports:
      - "2222:2222"
    volumes:
      - ./scripts/start-vm.sh:/root/start-vm.sh
      - ./authorized_keys:/root/share/authorized_keys
    command: >
      /bin/bash -c "
      tmux new-session -d -s open-rdma;
      tmux send-keys -t open-rdma 'cd /root && ./start-vm.sh' C-m;
      tmux attach-session -t open-rdma;
      "